import { Complaint, IncidentEvent, ResponsePlan, IncidentUpdate } from '../types/complaint';
import { Incident } from '../types/incident';

// Helper for dates relative to now
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const minsAgo = (mins: number) => new Date(Date.now() - mins * 60 * 1000).toISOString();
const daysAgo = (days: number, hourOffset = 0) => new Date(Date.now() - (days * 24 + hourOffset) * 60 * 60 * 1000).toISOString();

export const DEMO_COMPLAINTS: Complaint[] = [
  // ── TODAY (Day 0) ──
  // 1. Critical Fire & LPG Explosion (Active)
  {
    id: '11111111-1111-4111-8111-111111111111',
    reporter_id: null,
    device_session_id: 'demo-session-fire-01',
    category: 'Fire',
    description: 'Major commercial LPG cylinder explosion and active blaze at Hazratganj Market. Thick smoke engulfing adjacent shops, people trapped on 2nd floor.',
    photo_url: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'यहाँ हजरतगंज मार्केट में एलपीजी सिलेंडर ब्लास्ट हुआ है, आग बहुत तेज़ी से दुकानों में फैल रही है, तुरंत फायर ब्रिगेड और एम्बुलेंस भेजिए!',
    latitude: 26.8467,
    longitude: 80.9462,
    gps_accuracy: 8.5,
    address: 'Shop 42, Commercial Complex, Hazratganj, Lucknow, Uttar Pradesh 226001',
    risk_score: 95,
    risk_level: 'CRITICAL',
    confidence_score: 94,
    confidence_basis: {
      input_completeness: 95,
      category_clarity: 95,
      location_availability: 95,
      evidence_strength: 95,
    },
    incident_intelligence: {
      incident_type: 'Fire Outbreak',
      severity: 'CRITICAL',
      risk_score: 95,
      confidence_score: 94,
      people_affected_estimate: '5+',
      possible_injury: true,
      location_confirmed: true,
      recommended_action: 'Immediate fire brigade dispatch and multi-casualty medical triage',
      decision_factors: [
        'Fire / hazardous conditions reported',
        'Trapped individuals indicated',
        'Immediate danger indicated',
        'Precise GPS fix available (±9m)',
      ],
    },
    response_plan: {
      incident_id: '11111111-1111-4111-8111-111111111111',
      priority: 'CRITICAL',
      primary_response: {
        id: 'fire_central_01',
        name: 'Hazratganj Central Fire Station (Engine-4 & 9)',
        type: 'fire_station',
        distance_km: 1.4,
        estimated_eta_minutes: 5,
        is_estimate: true,
        phone: '101 / 0522-2200101',
        address: 'MG Marg, Hazratganj',
        directions_url: 'https://maps.google.com/?q=26.8480,80.9490',
        latitude: 26.8480,
        longitude: 80.9490,
        status: 'Dispatched',
      },
      secondary_response: {
        id: 'hosp_trauma_01',
        name: 'King George Emergency Trauma Center',
        type: 'hospital',
        distance_km: 2.2,
        estimated_eta_minutes: 8,
        is_estimate: true,
        phone: '108 / 0522-2257540',
        address: 'Shah Mina Road, Chowk',
        directions_url: 'https://maps.google.com/?q=26.8680,80.9160',
        latitude: 26.8680,
        longitude: 80.9160,
        status: 'Alerted',
      },
      all_responders: [],
      recommended_action: 'Dispatch Fire Tender unit, alert Trauma Hospital, and establish perimeter control.',
      human_confirmation_required: true,
      confirmation_status: 'CONFIRMED',
      confirmed_at: minsAgo(15),
      confirmed_by: 'CHIEF_DISPATCHER_01',
      responder_status: {
        police: 'Dispatched',
        hospital: 'Alerted',
        ambulance: 'En route',
        citizen: 'Safe / Awaiting assistance',
      },
      created_at: minsAgo(18),
    },
    status: 'Emergency Response',
    routed_department: 'Fire & Emergency Services',
    created_at: minsAgo(18),
    updated_at: minsAgo(15),
  },

  // 2. Critical Road Accident & Pileup (Active)
  {
    id: '22222222-2222-4222-8222-222222222222',
    reporter_id: null,
    device_session_id: 'demo-session-accident-02',
    category: 'Accident',
    description: 'Head-on collision between car and commuter bus at Gomti Nagar flyover. Unconscious passenger with heavy bleeding, traffic blocked.',
    photo_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'Severe crash on the flyover junction, car collided with a bus, driver is unconscious and passenger is bleeding heavily, send ambulance fast!',
    latitude: 26.8520,
    longitude: 80.9950,
    gps_accuracy: 10.0,
    address: 'Flyover Junction, Shaheed Path, Gomti Nagar, Lucknow 226010',
    risk_score: 94,
    risk_level: 'CRITICAL',
    confidence_score: 92,
    confidence_basis: {
      input_completeness: 95,
      category_clarity: 95,
      location_availability: 95,
      evidence_strength: 95,
    },
    incident_intelligence: {
      incident_type: 'Road Accident',
      severity: 'CRITICAL',
      risk_score: 94,
      confidence_score: 92,
      people_affected_estimate: '2+',
      possible_injury: true,
      location_confirmed: true,
      recommended_action: 'Immediate medical and police escalation',
      decision_factors: [
        'Accident detected',
        'Possible injury mentioned',
        'Immediate danger indicated',
        'Precise GPS fix available (±10m)',
      ],
    },
    response_plan: {
      incident_id: '22222222-2222-4222-8222-222222222222',
      priority: 'CRITICAL',
      primary_response: {
        id: 'hosp_ram_manohar',
        name: 'Dr. Ram Manohar Lohia Hospital & Trauma',
        type: 'hospital',
        distance_km: 1.8,
        estimated_eta_minutes: 7,
        is_estimate: true,
        phone: '108 / 0522-6692000',
        address: 'Vibhuti Khand, Gomti Nagar',
        directions_url: 'https://maps.google.com/?q=26.8650,81.0020',
        latitude: 26.8650,
        longitude: 81.0020,
        status: 'Dispatched',
      },
      secondary_response: {
        id: 'police_gomti_nagar',
        name: 'Gomti Nagar Police Station',
        type: 'police',
        distance_km: 2.1,
        estimated_eta_minutes: 8,
        is_estimate: true,
        phone: '100 / 112',
        address: 'Vipin Khand, Gomti Nagar',
        directions_url: 'https://maps.google.com/?q=26.8580,80.9820',
        latitude: 26.8580,
        longitude: 80.9820,
        status: 'Dispatched',
      },
      all_responders: [],
      recommended_action: 'Dispatch medical response and notify nearest police unit.',
      human_confirmation_required: true,
      confirmation_status: 'CONFIRMED',
      confirmed_at: minsAgo(30),
      confirmed_by: 'DISPATCH_OFFICER_42',
      responder_status: {
        police: 'Dispatched',
        hospital: 'Alerted',
        ambulance: 'En route',
        citizen: 'Safe / Awaiting assistance',
      },
      created_at: minsAgo(45),
    },
    status: 'Emergency Response',
    routed_department: 'Police Dept + Nearest Hospital Emergency Trauma',
    created_at: minsAgo(45),
    updated_at: minsAgo(30),
  },

  // 3. Duplicate Accident Report linked to #22222222
  {
    id: '22222222-2222-4222-8222-333333333333',
    reporter_id: null,
    device_session_id: 'demo-session-accident-02-dup',
    category: 'Accident',
    description: 'Car flipped over at Gomti Nagar flyover, large crowd gathered and ambulance needed.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Accident near flyover, car is completely smashed and blocking vehicles.',
    latitude: 26.8523,
    longitude: 80.9953,
    gps_accuracy: 12.0,
    address: 'Near Shaheed Path Flyover Ramp, Gomti Nagar, Lucknow',
    risk_score: 90,
    risk_level: 'CRITICAL',
    confidence_score: 88,
    duplicate_info: {
      is_duplicate: true,
      primary_incident_id: '22222222-2222-4222-8222-222222222222',
      similarity_score: 0.88,
      duplicate_count: 2,
      reasons: [
        'Within 150m (38m from primary report)',
        'Within 45 minutes (10m ago)',
        'Matching category: Accident',
        'High descriptive overlap (72% match)',
      ],
    },
    status: 'In Progress',
    routed_department: 'Police Dept + Nearest Hospital Emergency Trauma',
    created_at: minsAgo(35),
    updated_at: minsAgo(30),
  },

  // 4. Medical Emergency (Charbagh)
  {
    id: '55555555-5555-4555-8555-555555555555',
    reporter_id: null,
    device_session_id: 'demo-session-med-05',
    category: 'Medical Emergency',
    description: 'Elderly citizen collapsed with acute cardiac distress, unconscious and unresponsive at Charbagh station waiting area.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'ইয়ালৈ এম্বুলেন্স আৰু জৰুৰীকালীন চিকিৎসা সোনকালে পঠাওক, এজন মানুহ অচেতন হৈ পৰিছে!',
    latitude: 26.8320,
    longitude: 80.9210,
    gps_accuracy: 6.0,
    address: 'Platform 1 Waiting Hall, Charbagh Railway Station, Lucknow 226004',
    risk_score: 88,
    risk_level: 'CRITICAL',
    confidence_score: 90,
    incident_intelligence: {
      incident_type: 'Medical Emergency',
      severity: 'CRITICAL',
      risk_score: 88,
      confidence_score: 90,
      people_affected_estimate: '1',
      possible_injury: true,
      location_confirmed: true,
      recommended_action: 'Immediate ambulance dispatch and hospital alert',
      decision_factors: [
        'Possible injury mentioned',
        'Immediate danger indicated',
        'High-risk category: Medical Emergency',
        'Precise GPS fix available (±6m)',
      ],
    },
    status: 'Critical Incident',
    routed_department: 'Nearest Hospital Emergency & Ambulance (108)',
    created_at: minsAgo(10),
    updated_at: minsAgo(10),
  },

  // 5. Civic Issue: Water Pipeline Burst
  {
    id: '33333333-3333-4333-8333-333333333333',
    reporter_id: null,
    device_session_id: 'demo-session-water-03',
    category: 'Water leakage',
    description: 'High-pressure primary water transmission pipeline burst causing severe road flooding and asphalt subsidence near Metro Pillar 140.',
    photo_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'Large water pipeline burst under the road near Metro pillar 140, water is gushing out heavily and flooding the street.',
    latitude: 26.8700,
    longitude: 80.9600,
    gps_accuracy: 5.0,
    address: 'Near Metro Pillar 140, University Road, Lucknow 226007',
    risk_score: 48,
    risk_level: 'MEDIUM',
    confidence_score: 85,
    status: 'Verified',
    routed_department: 'Municipal Corporation — Water & Sewerage Dept',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1),
  },

  // 6. Civic Issue: Streetlight Failure
  {
    id: '44444444-4444-4444-8444-444444444444',
    reporter_id: null,
    device_session_id: 'demo-session-power-04',
    category: 'Streetlight problems',
    description: 'Streetlight feeder failure causing total darkness across 5th Cross for 4 consecutive nights. Open excavation trench left unprotected.',
    photo_url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'The entire street lighting line has been non-functional for four nights and an open trench on 5th cross is completely unlit.',
    latitude: 26.8400,
    longitude: 80.9300,
    gps_accuracy: 8.0,
    address: '5th Cross Road, Sector B, Aliganj, Lucknow 226024',
    risk_score: 22,
    risk_level: 'LOW',
    confidence_score: 80,
    status: 'Reported',
    routed_department: 'Municipal Corporation — Electrical Dept',
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
  },

  // ── YESTERDAY (Day 1) ──
  // 7. Road Damage (Resolved)
  {
    id: '66666666-6666-4666-8666-666666666666',
    reporter_id: null,
    device_session_id: 'demo-session-road-06',
    category: 'Road damage',
    description: 'Dangerous deep pothole cluster causing two-wheeler skids near IT Chauraha main intersection.',
    photo_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'Very big pothole cluster near IT crossing, bikes are falling down.',
    latitude: 26.8720,
    longitude: 80.9380,
    gps_accuracy: 6.0,
    address: 'IT Chauraha, Faizabad Road, Lucknow 226007',
    risk_score: 45,
    risk_level: 'MEDIUM',
    confidence_score: 91,
    status: 'Resolved',
    routed_department: 'Public Works Dept (PWD) / Municipal Roads',
    created_at: daysAgo(1, 6),
    updated_at: daysAgo(1, 2),
  },

  // 8. Garbage/waste accumulation (Resolved)
  {
    id: '77777777-7777-4777-8777-777777777777',
    reporter_id: null,
    device_session_id: 'demo-session-waste-07',
    category: 'Garbage/waste',
    description: 'Overflowing community dumpster blocking pedestrian walkway and creating severe sanitary hazard outside residential colony.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Garbage dump is overflowing completely on the road, bad smell and dogs blocking entry.',
    latitude: 26.8850,
    longitude: 80.9520,
    gps_accuracy: 7.0,
    address: 'Sector 8 Market Gate, Mahanagar, Lucknow 226006',
    risk_score: 35,
    risk_level: 'MEDIUM',
    confidence_score: 87,
    status: 'Resolved',
    routed_department: 'Municipal Corporation — Solid Waste Management',
    created_at: daysAgo(1, 10),
    updated_at: daysAgo(1, 7),
  },

  // 9. Noise Complaint (Resolved)
  {
    id: '88888888-8888-4888-8888-888888888888',
    reporter_id: null,
    device_session_id: 'demo-session-noise-08',
    category: 'Noise complaints',
    description: 'High-decibel industrial generator running past midnight without sound dampener in quiet residential zone.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Heavy generator noise after 1 AM keeping entire street awake.',
    latitude: 26.8610,
    longitude: 80.9750,
    gps_accuracy: 10.0,
    address: 'Vipul Khand 3, Gomti Nagar, Lucknow 226010',
    risk_score: 28,
    risk_level: 'LOW',
    confidence_score: 83,
    status: 'Resolved',
    routed_department: 'Lucknow Police / Pollution Control Board',
    created_at: daysAgo(1, 14),
    updated_at: daysAgo(1, 12),
  },

  // ── 2 DAYS AGO (Day 2) ──
  // 10. Harassment / Women Safety (Resolved)
  {
    id: '99999999-9999-4999-8999-999999999999',
    reporter_id: null,
    device_session_id: 'demo-session-safe-09',
    category: 'Harassment',
    description: 'Group of men loitering near ladies coaching center passing lewd remarks and blocking footpath.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Some men are harassing students outside coaching center, police patrol needed immediately.',
    latitude: 26.8490,
    longitude: 80.9390,
    gps_accuracy: 5.0,
    address: 'Near Women College Gate, Ashok Marg, Hazratganj, Lucknow',
    risk_score: 76,
    risk_level: 'HIGH',
    confidence_score: 93,
    status: 'Resolved',
    routed_department: 'UP Police Women Powerline (1090) & Hazratganj PS',
    created_at: daysAgo(2, 4),
    updated_at: daysAgo(2, 2),
  },

  // 11. Suspicious Activity (Resolved)
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    reporter_id: null,
    device_session_id: 'demo-session-susp-10',
    category: 'Suspicious activity',
    description: 'Unattended metallic briefcase left chained to metro staircase railing for over 3 hours.',
    photo_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'There is an unattended locked briefcase at the metro exit gate with nobody around.',
    latitude: 26.8395,
    longitude: 80.9230,
    gps_accuracy: 4.5,
    address: 'Metro Gate 2, Charbagh Metro Station, Lucknow',
    risk_score: 82,
    risk_level: 'CRITICAL',
    confidence_score: 89,
    status: 'Resolved',
    routed_department: 'Metro Security / Anti-Sabotage Squad / Local Police',
    created_at: daysAgo(2, 8),
    updated_at: daysAgo(2, 6),
  },

  // 12. Water Leakage (Resolved)
  {
    id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    reporter_id: null,
    device_session_id: 'demo-session-water-11',
    category: 'Water leakage',
    description: 'Underground supply conduit ruptured during fiber optic trenching, flooding basement parking.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Water line broken during digging, basement getting flooded.',
    latitude: 26.8550,
    longitude: 80.9420,
    gps_accuracy: 8.0,
    address: 'Sapru Marg Commercial Complex, Lucknow 226001',
    risk_score: 52,
    risk_level: 'MEDIUM',
    confidence_score: 86,
    status: 'Resolved',
    routed_department: 'Municipal Corporation — Water & Sewerage Dept',
    created_at: daysAgo(2, 14),
    updated_at: daysAgo(2, 11),
  },

  // 13. Other civic issues: Broken manhole cover (Resolved)
  {
    id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    reporter_id: null,
    device_session_id: 'demo-session-drain-12',
    category: 'Other civic issues',
    description: 'Heavy cast-iron storm drain cover missing, exposing 10-foot drop right near school crossing.',
    photo_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    video_url: null,
    voice_transcript: 'Open manhole right outside primary school gate, very dangerous for kids.',
    latitude: 26.8680,
    longitude: 80.9290,
    gps_accuracy: 5.0,
    address: 'Near St. Francis Primary School, Cantt Road, Lucknow',
    risk_score: 68,
    risk_level: 'HIGH',
    confidence_score: 95,
    status: 'Resolved',
    routed_department: 'Municipal Corporation — Drainage & Sewerage',
    created_at: daysAgo(2, 18),
    updated_at: daysAgo(2, 15),
  },

  // ── 3 DAYS AGO (Day 3) ──
  // 14. Road Accident (Resolved)
  {
    id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
    reporter_id: null,
    device_session_id: 'demo-session-acc-13',
    category: 'Accident',
    description: 'Auto rickshaw overturned after tire burst on main highway. 3 passengers sustained minor bruises.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Auto overturned on highway, people got hurt, need police and first aid.',
    latitude: 26.8210,
    longitude: 80.9100,
    gps_accuracy: 9.0,
    address: 'Kanpur Road, Near Transport Nagar, Lucknow',
    risk_score: 72,
    risk_level: 'HIGH',
    confidence_score: 91,
    status: 'Resolved',
    routed_department: 'Traffic Police & Emergency 108 Ambulance',
    created_at: daysAgo(3, 5),
    updated_at: daysAgo(3, 4),
  },

  // 15. Fire (Kitchen blaze in restaurant - Resolved)
  {
    id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
    reporter_id: null,
    device_session_id: 'demo-session-fire-14',
    category: 'Fire',
    description: 'Commercial kitchen exhaust flue caught fire. Controlled by staff and arriving fire tender.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Kitchen chimney on fire at restaurant, smoke filling dining area.',
    latitude: 26.8480,
    longitude: 80.9500,
    gps_accuracy: 6.0,
    address: 'Naval Kishore Road, Hazratganj, Lucknow',
    risk_score: 78,
    risk_level: 'HIGH',
    confidence_score: 92,
    status: 'Resolved',
    routed_department: 'Fire & Emergency Services',
    created_at: daysAgo(3, 11),
    updated_at: daysAgo(3, 9),
  },

  // 16. Garbage / Hazardous chemical dumping (In Progress)
  {
    id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
    reporter_id: null,
    device_session_id: 'demo-session-waste-15',
    category: 'Garbage/waste',
    description: 'Illegal dumping of industrial paint sludge into open storm canal.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Truck dumped industrial paint waste into the open canal, pungent smell.',
    latitude: 26.8920,
    longitude: 80.9810,
    gps_accuracy: 11.0,
    address: 'Indira Nagar Canal Road, Sector 14, Lucknow',
    risk_score: 65,
    risk_level: 'HIGH',
    confidence_score: 84,
    status: 'In Progress',
    routed_department: 'Pollution Control Board & Municipal Sanitation',
    created_at: daysAgo(3, 16),
    updated_at: daysAgo(3, 12),
  },

  // ── 4 DAYS AGO (Day 4) ──
  // 17. Medical Emergency: Heatstroke (Resolved)
  {
    id: '10101010-1010-4010-8010-101010101010',
    reporter_id: null,
    device_session_id: 'demo-session-med-16',
    category: 'Medical Emergency',
    description: 'Traffic warden collapsed during afternoon shift due to severe heatstroke and dehydration.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Traffic policeman fainted on duty due to extreme heat, need ambulance.',
    latitude: 26.8420,
    longitude: 80.9410,
    gps_accuracy: 5.0,
    address: 'Parivartan Chowk, Lucknow',
    risk_score: 85,
    risk_level: 'CRITICAL',
    confidence_score: 96,
    status: 'Resolved',
    routed_department: 'Civil Hospital Emergency Trauma & Ambulance 108',
    created_at: daysAgo(4, 4),
    updated_at: daysAgo(4, 3),
  },

  // 18. Streetlight Blackout (Resolved)
  {
    id: '20202020-2020-4020-8020-202020202020',
    reporter_id: null,
    device_session_id: 'demo-session-light-17',
    category: 'Streetlight problems',
    description: '12 LED streetlights damaged during thunderstorm, whole residential lane plunged into darkness.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'All lights on lane 4 are off after storm, very dark and unsafe.',
    latitude: 26.8640,
    longitude: 80.9190,
    gps_accuracy: 7.0,
    address: 'Lane 4, Chowk Market Area, Lucknow',
    risk_score: 18,
    risk_level: 'LOW',
    confidence_score: 88,
    status: 'Resolved',
    routed_department: 'Municipal Corporation — Electrical Dept',
    created_at: daysAgo(4, 12),
    updated_at: daysAgo(4, 8),
  },

  // 19. Road Damage: Cave-in (In Progress)
  {
    id: '30303030-3030-4030-8030-303030303030',
    reporter_id: null,
    device_session_id: 'demo-session-road-18',
    category: 'Road damage',
    description: 'Road cave-in formed after underground sewer line collapse on major bus route.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Big road cave in near polytechnic crossing, bus route affected.',
    latitude: 26.8810,
    longitude: 80.9990,
    gps_accuracy: 6.0,
    address: 'Polytechnic Chauraha, Ring Road, Lucknow',
    risk_score: 62,
    risk_level: 'HIGH',
    confidence_score: 90,
    status: 'In Progress',
    routed_department: 'PWD & Lucknow Jal Sansthan',
    created_at: daysAgo(4, 18),
    updated_at: daysAgo(4, 10),
  },

  // ── 5 DAYS AGO (Day 5) ──
  // 20. Other civic: Fallen Tree Branch (Resolved)
  {
    id: '40404040-4040-4040-8040-404040404040',
    reporter_id: null,
    device_session_id: 'demo-session-tree-19',
    category: 'Other civic issues',
    description: 'Large banyan tree branch snapped and resting on overhead electricity cables.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Big tree branch fallen on power lines, sparking danger.',
    latitude: 26.8560,
    longitude: 80.9320,
    gps_accuracy: 5.5,
    address: 'Gokhale Marg, Hazratganj, Lucknow',
    risk_score: 58,
    risk_level: 'MEDIUM',
    confidence_score: 93,
    status: 'Resolved',
    routed_department: 'Forestry Wing & LESA Electricity Board',
    created_at: daysAgo(5, 7),
    updated_at: daysAgo(5, 5),
  },

  // 21. Noise complaint (Resolved)
  {
    id: '50505050-5050-4050-8050-505050505050',
    reporter_id: null,
    device_session_id: 'demo-session-noise-20',
    category: 'Noise complaints',
    description: 'Loud DJ music playing outside hospital silent zone past permitted hours.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Loud music near Balrampur Hospital at 11:30 PM.',
    latitude: 26.8620,
    longitude: 80.9250,
    gps_accuracy: 8.0,
    address: 'Hospital Road, Golaganj, Lucknow',
    risk_score: 32,
    risk_level: 'MEDIUM',
    confidence_score: 87,
    status: 'Resolved',
    routed_department: 'Lucknow Police',
    created_at: daysAgo(5, 15),
    updated_at: daysAgo(5, 14),
  },

  // ── 6 DAYS AGO (Day 6) ──
  // 22. Medical Emergency (Resolved)
  {
    id: '60606060-6060-4060-8060-606060606060',
    reporter_id: null,
    device_session_id: 'demo-session-med-21',
    category: 'Medical Emergency',
    description: 'Pregnant woman in critical labor requiring emergency hospital transport from remote residential colony.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Emergency delivery case, send 102 ambulance urgently.',
    latitude: 26.8990,
    longitude: 80.9650,
    gps_accuracy: 7.0,
    address: 'Kalyanpur Ring Road, Lucknow',
    risk_score: 86,
    risk_level: 'CRITICAL',
    confidence_score: 95,
    status: 'Resolved',
    routed_department: '102/108 Emergency Medical Services & Queen Mary Hospital',
    created_at: daysAgo(6, 8),
    updated_at: daysAgo(6, 7),
  },

  // 23. Road Damage (Resolved)
  {
    id: '70707070-7070-4070-8070-707070707070',
    reporter_id: null,
    device_session_id: 'demo-session-road-22',
    category: 'Road damage',
    description: 'Widespread bitumen surface peeling on newly paved flyover approach road.',
    photo_url: null,
    video_url: null,
    voice_transcript: 'Road surface is breaking apart on the flyover ramp.',
    latitude: 26.8370,
    longitude: 80.9150,
    gps_accuracy: 9.0,
    address: 'Mawaiya Overbridge Approach, Lucknow',
    risk_score: 38,
    risk_level: 'MEDIUM',
    confidence_score: 82,
    status: 'Resolved',
    routed_department: 'Public Works Department (PWD)',
    created_at: daysAgo(6, 16),
    updated_at: daysAgo(6, 11),
  },
];

export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 'a1111111-1111-4111-8111-111111111111',
    complaint_id: '11111111-1111-4111-8111-111111111111',
    incident_type: 'Fire',
    urgency_score: 95,
    latitude: 26.8467,
    longitude: 80.9462,
    gps_accuracy: 8.5,
    summary: 'Major commercial LPG gas cylinder explosion and active blaze at Hazratganj Market.',
    video_room_url: 'https://meet.jit.si/vera-incident-11111111-live',
    created_at: minsAgo(18),
    escalated_at: minsAgo(18),
    resolved_at: null,
  },
  {
    id: 'a2222222-2222-4222-8222-222222222222',
    complaint_id: '22222222-2222-4222-8222-222222222222',
    incident_type: 'Accident',
    urgency_score: 94,
    latitude: 26.8520,
    longitude: 80.9950,
    gps_accuracy: 10.0,
    summary: 'Head-on collision between car and commuter bus at Gomti Nagar flyover.',
    video_room_url: 'https://meet.jit.si/vera-incident-22222222-live',
    created_at: minsAgo(45),
    escalated_at: minsAgo(45),
    resolved_at: null,
  },
  {
    id: 'a5555555-5555-4555-8555-555555555555',
    complaint_id: '55555555-5555-4555-8555-555555555555',
    incident_type: 'Medical Emergency',
    urgency_score: 88,
    latitude: 26.8320,
    longitude: 80.9210,
    gps_accuracy: 6.0,
    summary: 'Elderly citizen collapsed with acute cardiac distress at Charbagh station.',
    video_room_url: 'https://meet.jit.si/vera-incident-55555555-live',
    created_at: minsAgo(10),
    escalated_at: minsAgo(10),
    resolved_at: null,
  },
];

export const DEMO_EVENTS: IncidentEvent[] = [
  // Fire Events (#11111111...)
  {
    id: 'e1111111-1111-4111-8111-111111111101',
    complaint_id: '11111111-1111-4111-8111-111111111111',
    old_status: null,
    new_status: 'Reported',
    message: 'Citizen submitted emergency voice report. Translated from Hindi.',
    created_at: minsAgo(18),
    changed_by: 'CITIZEN',
  },
  {
    id: 'e1111111-1111-4111-8111-111111111102',
    complaint_id: '11111111-1111-4111-8111-111111111111',
    old_status: 'Reported',
    new_status: 'Critical Incident',
    message: '🚨 VERA Risk Engine escalated incident to Critical (Score: 95/100, Confidence: 94%).',
    created_at: minsAgo(18),
    changed_by: 'VERA_RISK_ENGINE',
  },
  {
    id: 'e1111111-1111-4111-8111-111111111103',
    complaint_id: '11111111-1111-4111-8111-111111111111',
    old_status: 'Critical Incident',
    new_status: 'Emergency Response',
    message: 'Operator confirmed Response Plan. Dispatched Hazratganj Fire Engine-4 (~5m ETA) & King George Trauma (~8m ETA).',
    created_at: minsAgo(15),
    changed_by: 'CHIEF_DISPATCHER_01',
  },

  // Accident Events (#22222222...)
  {
    id: 'e2222222-2222-4222-8222-222222222201',
    complaint_id: '22222222-2222-4222-8222-222222222222',
    old_status: null,
    new_status: 'Reported',
    message: 'Citizen reported collision on flyover.',
    created_at: minsAgo(45),
    changed_by: 'CITIZEN',
  },
  {
    id: 'e2222222-2222-4222-8222-222222222202',
    complaint_id: '22222222-2222-4222-8222-222222222222',
    old_status: 'Reported',
    new_status: 'Emergency Response',
    message: 'Ambulance and Police unit dispatched.',
    created_at: minsAgo(30),
    changed_by: 'DISPATCH_OFFICER_42',
  },

  // Resolved Events with Real Durations
  // 66666666 (Road Damage - Resolved in 240 mins)
  {
    id: 'e6666666-01',
    complaint_id: '66666666-6666-4666-8666-666666666666',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'PWD emergency maintenance squad cold-patched all pothole clusters and restored road surface.',
    created_at: daysAgo(1, 2),
    changed_by: 'PWD_FIELD_SUPERVISOR',
  },

  // 77777777 (Garbage - Resolved in 180 mins)
  {
    id: 'e7777777-01',
    complaint_id: '77777777-7777-4777-8777-777777777777',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Municipal sanitary compactor truck cleared dump site and disinfected area.',
    created_at: daysAgo(1, 7),
    changed_by: 'MUNICIPAL_SANITATION_HQ',
  },

  // 88888888 (Noise - Resolved in 120 mins)
  {
    id: 'e8888888-01',
    complaint_id: '88888888-8888-4888-8888-888888888888',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Night patrol unit inspected site and issued compliance warning; generator powered down.',
    created_at: daysAgo(1, 12),
    changed_by: 'POLICE_PATROL_04',
  },

  // 99999999 (Harassment - Resolved in 120 mins)
  {
    id: 'e9999999-01',
    complaint_id: '99999999-9999-4999-8999-999999999999',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Pink Police mobile patrol intercepted individuals, conducted identification verification, and established continuous post.',
    created_at: daysAgo(2, 2),
    changed_by: 'WOMEN_POWERLINE_1090',
  },

  // aaaaaaaa (Suspicious Activity - Resolved in 120 mins)
  {
    id: 'eaaaaaaa-01',
    complaint_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Bomb disposal squad & CISF scanned briefcase; verified non-explosive personal luggage and safely retrieved.',
    created_at: daysAgo(2, 6),
    changed_by: 'METRO_SECURITY_COMMAND',
  },

  // bbbbbbbb (Water Leakage - Resolved in 180 mins)
  {
    id: 'ebbbbbbb-01',
    complaint_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Jal Sansthan isolation valve engaged and high-pressure sleeve weld completed.',
    created_at: daysAgo(2, 11),
    changed_by: 'JAL_SANSTHAN_CHIEF',
  },

  // cccccccc (Open Manhole - Resolved in 180 mins)
  {
    id: 'eccccccc-01',
    complaint_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Reinforced cement concrete cover installed with security locking ring.',
    created_at: daysAgo(2, 15),
    changed_by: 'DRAINAGE_SUPERVISOR_02',
  },

  // dddddddd (Overturned Auto - Resolved in 60 mins)
  {
    id: 'eddddddd-01',
    complaint_id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
    old_status: 'Emergency Response',
    new_status: 'Resolved',
    message: 'Injured treated on-site with first aid, wreckage moved to shoulder, traffic resumed.',
    created_at: daysAgo(3, 4),
    changed_by: 'TRAFFIC_OFFICER_12',
  },

  // eeeeeeee (Restaurant Fire - Resolved in 120 mins)
  {
    id: 'eeeeeeee-01',
    complaint_id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
    old_status: 'Emergency Response',
    new_status: 'Resolved',
    message: 'Hazratganj Fire Tender extinguished exhaust flue fire. Area ventilated and declared safe.',
    created_at: daysAgo(3, 9),
    changed_by: 'FIRE_STATION_OFFICER',
  },

  // 10101010 (Heatstroke - Resolved in 60 mins)
  {
    id: 'e1010101-01',
    complaint_id: '10101010-1010-4010-8010-101010101010',
    old_status: 'Emergency Response',
    new_status: 'Resolved',
    message: 'Patient administered IV fluids at Civil Hospital emergency room; vitals stabilized.',
    created_at: daysAgo(4, 3),
    changed_by: 'CIVIL_HOSP_EMS',
  },

  // 20202020 (Streetlights - Resolved in 240 mins)
  {
    id: 'e2020202-01',
    complaint_id: '20202020-2020-4020-8020-202020202020',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Feeder breaker replaced and 12 LED fixtures tested functional.',
    created_at: daysAgo(4, 8),
    changed_by: 'LESA_ELECTRICAL_CREW',
  },

  // 40404040 (Fallen Tree - Resolved in 120 mins)
  {
    id: 'e4040404-01',
    complaint_id: '40404040-4040-4040-8040-404040404040',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Forestry hydraulic saw crew removed overhang branch and power restored.',
    created_at: daysAgo(5, 5),
    changed_by: 'FORESTRY_DISPATCH',
  },

  // 50505050 (Noise near hospital - Resolved in 60 mins)
  {
    id: 'e5050505-01',
    complaint_id: '50505050-5050-4050-8050-505050505050',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Sound equipment impounded and organizers fined under Noise Pollution Rules.',
    created_at: daysAgo(5, 14),
    changed_by: 'POLICE_NIGHT_SQUAD',
  },

  // 60606060 (Maternal Emergency - Resolved in 60 mins)
  {
    id: 'e6060606-01',
    complaint_id: '60606060-6060-4060-8060-606060606060',
    old_status: 'Emergency Response',
    new_status: 'Resolved',
    message: 'Patient safely admitted to Queen Mary Hospital labor ward with ALS escort.',
    created_at: daysAgo(6, 7),
    changed_by: '102_ALS_PARAMEDIC',
  },

  // 70707070 (Road damage - Resolved in 300 mins)
  {
    id: 'e7070707-01',
    complaint_id: '70707070-7070-4070-8070-707070707070',
    old_status: 'Reported',
    new_status: 'Resolved',
    message: 'Surface re-milled and hot asphalt overlay applied.',
    created_at: daysAgo(6, 11),
    changed_by: 'PWD_QUALITY_CONTROL',
  },
];

export const DEMO_UPDATES: IncidentUpdate[] = [
  // Road Accident Incident Updates (#22222222...)
  {
    id: 'u2222222-001',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'citizen',
    author_name: 'Citizen (Witness)',
    author_role: 'Nearby Commuter',
    message: 'Two vehicles have collided. One passenger appears unconscious and severely injured.',
    update_type: 'situation_update',
    timestamp: minsAgo(44),
    photo_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u2222222-002',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'system',
    author_name: 'VERA',
    author_role: 'AI Dispatch Engine',
    message: 'Incident classified as Road Accident • Risk Score: 94/100 (CRITICAL) • Confidence: 92% • GPS fix verified (±10m).',
    update_type: 'status_update',
    timestamp: minsAgo(42),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u2222222-003',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'police',
    author_name: 'Gomti Nagar Police Control',
    author_role: 'Patrol Unit 08',
    message: 'Police unit dispatched to Gomti Nagar flyover. ETA 6 minutes.',
    update_type: 'dispatch_update',
    timestamp: minsAgo(40),
    is_pinned: false,
    is_verified_authority: true,
  },
  {
    id: 'u2222222-004',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'citizen',
    author_name: 'Citizen (Observer)',
    author_role: 'Witness on Scene',
    message: 'Traffic is completely blocked on the northbound lane. Vehicles backing up towards Shaheed Path.',
    update_type: 'situation_update',
    timestamp: minsAgo(38),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u2222222-005',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'hospital',
    author_name: 'Dr. Ram Manohar Lohia Hospital',
    author_role: 'Trauma Care Unit',
    message: 'Emergency trauma team is prepared. Advanced Life Support Ambulance dispatched (ETA ~7 min).',
    update_type: 'responder_update',
    timestamp: minsAgo(36),
    is_pinned: false,
    is_verified_authority: true,
  },
  {
    id: 'u2222222-006',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'police',
    author_name: 'Gomti Nagar Police Control',
    author_role: 'Officer In-Charge',
    message: 'Unit arrived at location. Perimeter secured and preliminary traffic diversion activated.',
    update_type: 'responder_update',
    timestamp: minsAgo(32),
    is_pinned: false,
    is_verified_authority: true,
  },
  {
    id: 'u2222222-007',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'citizen',
    author_name: 'Citizen (On Scene)',
    author_role: 'First Responder Commuter',
    message: 'Ambulance has arrived. Medical personnel are assisting the injured driver.',
    update_type: 'help_arrived',
    timestamp: minsAgo(28),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u2222222-008',
    incident_id: '22222222-2222-4222-8222-222222222222',
    author_type: 'authority',
    author_name: 'Traffic Command Authority',
    author_role: 'Senior Traffic Supervisor',
    message: 'Road partially cleared on the right lane. Crane en route for vehicle removal. Single-lane movement restored.',
    update_type: 'resolution_update',
    timestamp: minsAgo(20),
    is_pinned: true,
    is_verified_authority: true,
  },

  // Fire Incident Updates (#11111111...)
  {
    id: 'u1111111-001',
    incident_id: '11111111-1111-4111-8111-111111111111',
    author_type: 'citizen',
    author_name: 'Shop Owner (Citizen)',
    author_role: 'Hazratganj Market Vendor',
    message: 'LPG cylinder exploded inside shop #42. Fire spreading to adjacent garments store. People evacuating.',
    update_type: 'situation_update',
    timestamp: minsAgo(17),
    photo_url: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?auto=format&fit=crop&w=800&q=80',
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u1111111-002',
    incident_id: '11111111-1111-4111-8111-111111111111',
    author_type: 'system',
    author_name: 'VERA',
    author_role: 'AI Risk Engine',
    message: 'Critical Fire Alarm triggered (Risk Score: 95/100). Nearest Fire Engine: Hazratganj Central (1.4 km, ~5 min ETA).',
    update_type: 'status_update',
    timestamp: minsAgo(16),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u1111111-003',
    incident_id: '11111111-1111-4111-8111-111111111111',
    author_type: 'authority',
    author_name: 'Hazratganj Fire Service',
    author_role: 'Station Officer',
    message: 'Engine-4 and Engine-9 en route with foam tenders. Gas supply shutoff requested to power grid.',
    update_type: 'dispatch_update',
    timestamp: minsAgo(14),
    is_pinned: true,
    is_verified_authority: true,
  },
  {
    id: 'u1111111-004',
    incident_id: '11111111-1111-4111-8111-111111111111',
    author_type: 'citizen',
    author_name: 'Market Security Guard',
    author_role: 'Citizen / Security',
    message: '2nd floor occupants safely evacuated via emergency fire stairs. No casualties reported so far.',
    update_type: 'situation_update',
    timestamp: minsAgo(10),
    is_pinned: false,
    is_verified_authority: false,
  },

  // Civic Incident Updates: Water Pipeline (#33333333...)
  {
    id: 'u3333333-001',
    incident_id: '33333333-3333-4333-8333-333333333333',
    author_type: 'citizen',
    author_name: 'Citizen (Resident)',
    author_role: 'Area Resident',
    message: 'Water pipeline burst under road near Pillar 140. High pressure stream flooding road.',
    update_type: 'situation_update',
    timestamp: minsAgo(110),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u3333333-002',
    incident_id: '33333333-3333-4333-8333-333333333333',
    author_type: 'system',
    author_name: 'VERA',
    author_role: 'Civic Routing',
    message: 'Routed to Municipal Corporation — Water & Sewerage Dept. SLA: 4 hours.',
    update_type: 'status_update',
    timestamp: minsAgo(108),
    is_pinned: false,
    is_verified_authority: false,
  },
  {
    id: 'u3333333-003',
    author_type: 'authority',
    incident_id: '33333333-3333-4333-8333-333333333333',
    author_name: 'Jal Sansthan Maintenance Team',
    author_role: 'Field Supervisor',
    message: 'Main valve 14-B isolated to stop flooding. Repair crew with replacement sleeve dispatched.',
    update_type: 'status_update',
    timestamp: minsAgo(60),
    is_pinned: true,
    is_verified_authority: true,
  },
];
